services:
  web:
    build: .
    ports:
      - "3309:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://clase:uninorte1@db:3306/college_db
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=python3
      - MYSQL_DATABASE=college_db
      - MYSQL_USER=clase
      - MYSQL_PASSWORD=uninorte1
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
